/**
 * Shared TypeScript types for the Eventify platform.
 * Centralizes interfaces previously duplicated across page components.
 * When migrating to Supabase, update these to match the row types
 * generated by `supabase gen types typescript`.
 */

// ─── Event ────────────────────────────────────────────────────────────────────

export interface ExhibitorSponsor {
  id: string;
  name: string;
  logo?: string;
  photo?: string;
  bio: string;
  message?: string;
  final_message?: string;
  socials?: {
    instagram?: string;
    whatsapp?: string;
    website?: string;
  };
}

export interface EventData {
  id: string;
  name: string;
  slug: string;
  status: 'pre' | 'live' | 'post';
  date: string;
  countdown_active?: boolean;
  logo_url?: string;
  primary_color?: string;
  secondary_color?: string;
  bg_type?: 'color' | 'gradient' | 'pattern';
  bg_value?: string;
  bg_gradient_from?: string;
  bg_gradient_to?: string;
  bg_pattern_bg?: string;
  bg_pattern_fg?: string;
  tv_bg_type?: 'color' | 'gradient' | 'pattern';
  tv_bg_value?: string;
  tv_bg_gradient_from?: string;
  tv_bg_gradient_to?: string;
  tv_bg_pattern_bg?: string;
  tv_bg_pattern_fg?: string;
  tv_primary_color?: string;
  tv_secondary_color?: string;
  comment_moderation_enabled?: boolean;
  owner_text?: string;
  owner_photo?: string;
  post_event_message?: string;
  summary_file_url?: string;
  has_official_photos?: boolean;
  exhibitors?: ExhibitorSponsor[];
  sponsors?: ExhibitorSponsor[];
  services?: ExhibitorSponsor[];
  custom_comments?: string[];
  upload_source?: 'camera' | 'gallery' | 'both';
  app_description?: string;
  app_whatsapp?: string;
  app_instagram?: string;
  app_website?: string;
  app_logo?: string;
  interactions_paused?: boolean;
  tv_show_ranking?: boolean;
}

// ─── Photo ────────────────────────────────────────────────────────────────────

export interface PhotoComment {
  id?: string;
  user: string;
  uid: string;
  text: string;
  timestamp: string;
  status: 'pending' | 'approved' | 'rejected';
}

export interface PhotoData {
  id: string;
  url: string;
  user_name: string;
  firebase_uid: string
  eventId: string;
  likes: number;
  reactions?: Record<string, number>;
  reacted_users?: string[];
  comments: PhotoComment[];
  timestamp: any;
  status: 'pending' | 'approved' | 'rejected';
  is_official?: boolean;
}

// ─── Print Order ──────────────────────────────────────────────────────────────

export interface PrintOrder {
  id: string;
  eventId: string;
  userId: string;
  userName: string;
  userEmail?: string;
  option: 'photos_only' | 'photos_album' | 'photos_album_stickers' | string;
  photoIds: string[];
  createdAt: any;
  status?: 'pending' | 'completed';
}

// ─── Notification ─────────────────────────────────────────────────────────────

export interface NotificationData {
  id: string;
  userId: string;
  title: string;
  body: string;
  read: boolean;
  link?: string;
  timestamp: any;
}
