/**
 * Shared TypeScript types for the Eventify platform.
 * Centralizes interfaces previously duplicated across page components.
 * When migrating to Supabase, update these to match the row types
 * generated by `supabase gen types typescript`.
 */

// ─── Event ────────────────────────────────────────────────────────────────────

export interface ExhibitorSponsor {
  id: string;
  name: string;
  logo?: string;
  photo?: string;
  bio: string;
  message?: string;
  final_message?: string;
  socials?: {
    instagram?: string;
    whatsapp?: string;
    website?: string;
  };
}

export interface EventData {
  id: string;
  name: string;
  slug: string;
  status: 'pre' | 'live' | 'post';
  date?: string | null;
  countdown_active?: boolean;
  logo_url?: string;
  primary_color?: string;
  secondary_color?: string;
  bg_type?: 'color' | 'gradient' | 'pattern';
  bg_value?: string;
  bg_gradient_from?: string;
  bg_gradient_to?: string;
  bg_pattern_bg?: string;
  bg_pattern_fg?: string;
  tv_bg_type?: 'color' | 'gradient' | 'pattern';
  tv_bg_value?: string;
  tv_bg_gradient_from?: string;
  tv_bg_gradient_to?: string;
  tv_bg_pattern_bg?: string;
  tv_bg_pattern_fg?: string;
  tv_primary_color?: string;
  tv_secondary_color?: string;
  comment_moderation_enabled?: boolean;
  owner_text?: string;
  owner_photo?: string;
  post_event_message?: string;
  summary_file_url?: string;
  has_official_photos?: boolean;
  services?: ExhibitorSponsor[];
  custom_comments?: string[];
  upload_source?: 'camera' | 'gallery' | 'both';
  exhibitor_categories?: string[];
  exhibitors_estimation?: number;
  public_evaluation_weight?: number;
  juror_evaluation_weight?: number;
  app_description?: string;
  app_whatsapp?: string;
  app_instagram?: string;
  app_website?: string;
  app_logo?: string;
  interactions_paused?: boolean;
  tv_show_ranking?: boolean;
  admin_emails?: string[];
  active_announcement_id?: string | null;
  announcement_trigger_at?: string | null;
  custom_sounds?: { id: string; name: string; url: string; }[] | null;
  active?: boolean;
}

export interface Announcement {
  id: string;
  event_id: string;
  title: string;
  message: string;
  bg_color?: string;
  text_color?: string;
  icon?: string;
  image_url?: string | null;
  audio_url?: string | null;
  show_duration_sec?: number;
  target_tv: boolean;
  target_app_popup: boolean;
  target_push: boolean;
  created_at: string;
  updated_at: string;
}

// ─── Post / Moderation ──────────────────────────────────────────────────────────

export interface PostReaction {
  id: string;
  post_id: string;
  user_id: string;
  type: string;
  created_at: string;
}

export interface PostComment {
  id: string;
  post_id: string;
  user_id: string;
  text: string;
  status: 'pending' | 'approved' | 'rejected';
  is_predefined: boolean;
  created_at: string;
  
  // Relational data from 'users' / Legacy fallback
  user?: any; // temporariamente any para aceitar tanto string (legado) quanto objeto {display_name}
  user_name?: string;
  uid?: string;
  timestamp?: string;
}

export interface PostData {
  id: string;
  event_id: string;
  user_id: string;
  image_url: string;
  status: 'pending' | 'approved' | 'rejected';
  is_official: boolean;
  printed: boolean;
  created_at: string;
  
  // Relational Data
  user?: {
    display_name: string;
    photo_url?: string;
  };
  reactions?: PostReaction[];
  comments?: PostComment[];
  
  // Aggregations
  reaction_counts?: Record<string, number>;

  // --- Legacy Mappings (Temporário para UI não quebrar) ---
  url?: string;
  user_name?: string;
  eventId?: string;
  likes?: number;
  timestamp?: any;
  reacted_users?: string[];
}

export type PhotoData = PostData;
export type PhotoComment = PostComment;

// ─── Print Order ──────────────────────────────────────────────────────────────

export interface PrintOrder {
  id: string;
  eventId: string;
  userId: string;
  userName: string;
  userEmail?: string;
  option: 'photos_only' | 'photos_album' | 'photos_album_stickers' | string;
  photoIds: string[];
  createdAt: any;
  status?: 'pending' | 'completed';
}

// ─── Exhibitors ───────────────────────────────────────────────────────────────

export interface Exhibitor {
  id: string;
  event_id: string;
  number: number;
  name: string;
  // Texto livre — opções vêm de events.exhibitor_categories (configurável por evento)
  category: string;
  description?: string | null;
  logo_url?: string | null;
  photo_url?: string | null;
  message?: string | null;
  final_message?: string | null;
  instagram_url?: string | null;
  whatsapp?: string | null;
  website_url?: string | null;
  status: 'active' | 'inactive';
  created_at: string;
  updated_at: string;
}

export interface Product {
  id: string;
  exhibitor_id: string;
  name: string;
  description?: string | null;
  price?: number | null;
  photos: string[];
  active: boolean;
  created_at: string;
  updated_at: string;
}

// ─── Sponsors ─────────────────────────────────────────────────────────────────

export type PartnerType = 'patrocinador' | 'apoiador' | 'servico';

export interface Partner {
  id: string;
  event_id: string;
  name: string;
  type: PartnerType;
  description?: string | null;
  photos: string[];
  // Uso interno — não exibido no app
  internal_contact?: string | null;
  // Valor do patrocínio — uso interno / relatório financeiro (só tipo patrocinador)
  sponsorship_value?: number | null;
  show_on_tv: boolean;
  show_on_feed: boolean;
  instagram_url?: string | null;
  whatsapp?: string | null;
  website_url?: string | null;
  order_index: number;
  active: boolean;
  created_at: string;
  updated_at: string;
}

export type LeadStatus = 'novo' | 'atendido' | 'pago' | 'retirado';

export interface Lead {
  id: string;
  product_id: string;
  exhibitor_id: string;
  customer_name: string;
  customer_phone: string;
  status: LeadStatus;
  created_at: string;
  product?: { name: string };
}

// ─── Auth / Usuários ─────────────────────────────────────────────────────────

export type UserRole = 'admin' | 'event_admin' | 'avaliador' | 'expositor' | 'participant';

export interface AppUser {
  id: string;
  supabase_user_id: string | null;
  email: string;
  display_name: string | null;
  photo_url: string | null;
  role: UserRole;
  event_id: string | null;
  exhibitor_id: string | null;
  created_at: string;
}

export interface UserEmailRole {
  email: string;
  role: UserRole;
  event_id: string | null;
  exhibitor_id: string | null;
  created_at: string;
}

// ─── Audit Log (Auditoria de alterações) ─────────────────────────────────────

export interface AuditChange {
  before: unknown;
  after: unknown;
}

export interface AuditLog {
  id: string;
  event_id: string;
  user_id: string | null;
  user_name: string | null;
  user_email: string | null;
  action: string;
  changes: Record<string, AuditChange>;
  created_at: string;
}

// ─── Evaluation (Avaliações) ──────────────────────────────────────────────────

export interface EvaluationCategory {
  id: string;
  event_id: string;
  name: string;
  weight: number;
  order_index: number;
  created_at: string;
}

export interface Evaluation {
  id: string;
  event_id: string;
  exhibitor_id: string;
  user_id: string;
  stars: number; // 1–5
  comment?: string | null;
  created_at: string;
}

export interface JurorEvaluation {
  id: string;
  event_id: string;
  exhibitor_id: string;
  user_id: string;
  category_id: string;
  score: number; // 0.00–5.00
  created_at: string;
}

// ─── Raffle (Sorteio) ────────────────────────────────────────────────────────

export interface RaffleTicket {
  id: string;
  event_id: string;
  user_id: string;
  created_at: string;
}

// ─── Visits (Analytics) ──────────────────────────────────────────────────────

export type VisitAction =
  | 'view_stand'
  | 'view_product'
  | 'click_lead'
  | 'click_instagram'
  | 'click_whatsapp'
  | 'click_website'
  | 'share';

export interface Visit {
  id: string;
  event_id: string;
  exhibitor_id?: string | null;
  product_id?: string | null;
  user_id?: string | null;
  session_id?: string | null;
  action: VisitAction;
  event_status?: 'pre' | 'live' | 'post' | null;
  created_at: string;
}

// ─── Ranking (View — view_exhibitor_rankings) ────────────────────────────────

export interface ExhibitorRanking {
  exhibitor_id: string;
  exhibitor_name: string;
  exhibitor_number: number;
  event_id: string;
  public_score: number;
  juror_score: number;
  final_score: number;
  public_votes_count: number;
  jurors_voted_count: number;
}

// ─── Notification ─────────────────────────────────────────────────────────────

export interface NotificationData {
  id: string;
  userId: string;
  title: string;
  body: string;
  read: boolean;
  link?: string;
  timestamp: any;
}
